version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp # plain dns
      - 53:53/udp
      # - 784:784/udp # dns over quicc
      # - 853:853/tcp # dns over tls
      - 3000:3000/tcp # web UI
    volumes:
      - /datadisk/server/data/adguardhome/data/work:/opt/adguardhome/work
      - /datadisk/server/data/adguardhome/data/conf:/opt/adguardhome/conf
