version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # currently using the first user from my system
    # uid: id -u user
    # gid: id -g group
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /app/data/jellyfin/config:/config
      - /app/data/jellyfin/cache:/cache
      - /app/media:/media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://flix.haicon.moe
