version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    pull_policy: always
    container_name: jellyfin
    # currently using the first user from my system
    # uid: id -u user
    # gid: id -g group
    user: 1000:1000
    # network_mode: "host"
    volumes:
      - /app/data/jellyfin/config:/config
      - /app/data/jellyfin/cache:/cache
      - /app/media:/media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://flix.haicon.moe

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - URL=haicon.moe
      - SUBDOMAINS=flix
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true #optional
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      # - EMAIL=<e-mail> #optional
      # - EXTRA_DOMAINS=<extradomains> #optional
      # - STAGING=false #optional
    volumes:
      - /app/data/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /app/data/ddclient/config:/config
    restart: unless-stopped
